import time
import os
import pyautogui

pyautogui.hotkey('ctrl','alt','t')
time.sleep(2)
pyautogui.write('sudo ifconfig wlx9cefd5fdd1b3 down')
time.sleep(.5)
pyautogui.press('enter')
time.sleep(.5)
pyautogui.write('Cyb3r0p$')
pyautogui.press('enter')
time.sleep(2)
pyautogui.write('sudo iwconfig wlx9cefd5fdd1b3 mode mon')
time.sleep(.5)
pyautogui.press('enter')
time.sleep(.5)
pyautogui.write('sudo ifconfig wlx9cefd5fdd1b3 up')
time.sleep(.5)
pyautogui.press('enter')
time.sleep(.5)
pyautogui.write('cd Desktop')
time.sleep(.5)
pyautogui.press('enter')
pyautogui.write('sudo tcpdump -i wlx9cefd5fdd1b3 -c 2000 -w Paswd.pcap')
time.sleep(.5)
pyautogui.press('enter')
time.sleep(840)
pyautogui.hotkey('ctrl','alt','c')
pyautogui.press('exit')
pyautogui.press('enter')
